### ISSUE TITLE
supermodel CLI not working behind corporate proxy

### ISSUE THREAD

**Issue by karsten-wagner** [supermodel/supermodel#13]
The supermodel CLI tools do not seem to consider local proxy settings (HTTP_PROXY & HTTPS_PROXY environment variables). When I execute a failed call from supermodel directly via curl, I am getting the expected result - so internet connectivity via proxy is available.

```bash
$ env | grep -i proxy
HTTP_PROXY=http://localhost:8888
HTTPS_PROXY=http://localhost:8888

$ supermodel schema validate supermodel/mymodel/
--> Failed supermodel\mymodel\supporting\Place.yaml:
unable to resolve the schema 'http://supermodel.io/gs1/properties/countryCode':
1. failed to fetch http://supermodel.io/gs1/properties/countryCode: FetchError: request to http://supermodel.io/gs1/properties/countryCode failed, reason: connect ECONNREFUSED 52.208.219.134:80
2. unable to load 'supermodel\gs1\properties\countryCode.yml' as 'http://supermodel.io/gs1/properties/countryCode'
no such file; supermodel\gs1\properties\countryCode.yml (or .yaml)

$ curl -s http://supermodel.io/gs1/properties/countryCode
{"$id":"http://supermodel.io/gs1/properties/countryCode","$schema":"http://json-schema.org/draft-07/schema#","$source":"http://gs1.org/voc/countryCode","title":"Country Code","type":"string","description":"Code specifying the country for the address using ISO 3166-1."}
```

I assume it is going back to this place:
https://github.com/supermodel/supermodel/blob/fdfc2cce6243dc03582cabab7873f5a771431ad3/packages/cli/src/commands/validate/validate.js#L73

There is no `agent` available in the options for the request - some references:
https://github.com/node-fetch/node-fetch#options
https://github.com/node-fetch/node-fetch/issues/79
https://github.com/TooTallNate/node-https-proxy-agent#https-module-example

It would be great to fix this also for the other commands...

**Comment by zdne** [comment]
Thanks for reporting @karsten-wagner we are going to look into this ASAP!

**Comment by karsten-wagner** [comment]
Seems to be stale for a while... closing this for hygiene of my issues list...

**Comment by zdne** [comment]
@karsten-wagner ok to close it. but would you still have a use for it?
